config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'oauth_callbacks',
    confirmations: 'email_confirmations'
  }

  root to: "questions#index"

  get :search, to: "search#index"

  resource :user do
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]

  concern :votable do
    member do
      post :positive, :negative
      delete :revote
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
  
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Voteable
  include Commentable

  belongs_to :user
  has_many :answers, -> { order best: :desc, created_at: :asc }, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  has_one :badge, dependent: :destroy

  accepts_nested_attributes_for :badge, allow_destroy: true,
                                        reject_if: :all_blank

  has_many_attached :files

  validates :title, :body, presence: true

  after_create_commit :subscribe_user!

  private

  def subscribe_user!
    user.subscribe!(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.with_attached_files.all
    render json: @questions
  end

  def show
    render json: @question
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner

    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy
      render json: @question, status: :ok
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  private

  def find_question
    @question ||= Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show update destroy]
  before_action :find_subscription, only: %i[show update]

  after_action :publish_question, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @comment = Comment.new
    @answer.links.build
  end

  def new
    @question = Question.new
    @question.links.build
    @question.build_badge
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question, notice: 'Question successfully created'
    else
      render :new
    end
  end

  def update
    @comment = Comment.new

    if current_user.author?(@question)
      @question.update(question_params)
      flash.now[:notice] = 'Question successfully edited'
    end
  end

  def destroy
    if current_user.author?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted'
    else
      render :show
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
    gon.question_id = @question.id
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                     links_attributes: [:id, :name, :url, :_destroy],
                                     badge_attributes: [:name, :image])
  end

  def publish_question
    return if @question.errors.present?

    ActionCable.server.broadcast(
      'question_channel',
      ApplicationController.render(
        partial: 'questions/question', 
        locals: { question: @question }
        )
      )
  end

  def find_subscription
    @subscription = current_user.subscriptions
      .find_by(question_id: @question) if current_user
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
tr
  td = link_to question.title, question_path(question)

app/views/questions/_section_question.html.slim
- cache [@question, current_user]
  - if current_user&.badges.present?
    span.border.border-light.card
      .card-header
        .received-badges
          h3 Received badges
          
      .card-body
        - current_user&.badges.each do |badge|
          h3 Badge: #{badge.name}
          p Question: #{badge.question.title} 
          p
            = image_tag badge.image, size: '100x100'

span.border.border-light.card
  .card-header
    h3 = @question.title
  .card-body
    p = @question.body
    p Author: #{@question.user.email}

    - if user_signed_in?
      = render partial: 'subscriptions/subscription', locals: { resource: @question }

    .question-comments
      = render partial: 'comments/list', locals: { resource: @question }

    .vote
      = render partial: 'votes/vote', locals: { resource: @question }

    - if @question.badge.present? && current_user&.author?(@question)
      .badge
        h3 Badge:
        p
          = @question.badge.name
        p
          = image_tag @question.badge.image, size: '100x100'

    .links
      p
        = render partial: 'links/list', locals: { resource: @question }

    .files
      p
        = render partial: 'attachments/attachment', locals: { resource: @question }

    - if can?(:destroy, @question)
      .edit-question
        = link_to 'Edit', '#', data: { question_id: @question.id },
                               class: 'edit-question-link btn btn-primary btn-sm'
        '  
        = link_to 'Delete', question_path(@question),
                            method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'btn btn-danger btn-sm'

        = form_with model: @question, class: 'hidden', html: { id: "edit-question-#{@question.id}" } do |f|
          .form-group  
            p= f.label :title
            p= f.text_field :title, id: :question_title

            p= f.label :body
            p= f.text_area :body, id: :question_body, rows: 3, cols: 31

            p
              = f.label :files
              ':
              = f.file_field :files, multiple: true, direct_upload: true

            = render partial: 'links/add', locals: { f: f }

          p
            = f.submit 'Save', class: 'btn btn-success'

app/views/questions/index.html.slim
- cache collection_cache_key :question do
  .questions
    span.border.border-light.card
      table.table.table-striped
        tr
          th = 'Questions'

          = render @questions

.container-sm.mt-1.mb-2
  - if user_signed_in? && can?(:create, Question)
    = link_to 'Ask', new_question_path, class: 'btn btn-success btn-block'

app/views/questions/new.html.slim
span.border.border-light.card.mb-2
  .card-header
    h3 New Question

  .card-body  
    = render 'shared/errors', resource: @question

    = form_with model: @question, local: true do |f|
      .question-fields
        p= f.label :title, 'Question title:'
        p= f.text_field :title

        p
          = f.label :body
          ':
        p= f.text_area :body, rows: 3, cols: 33

      p
        = f.label :files
        ':
        = f.file_field :files, multiple: true
      hr

      = render partial: 'links/add', locals: { f: f }
      hr

      .badge-fields
        p Add Bage
        = f.fields_for :badge do |badge|
          p= badge.label :name, 'Badge title:'
          p= badge.text_field :name
          p
            = badge.label :image
            ':
            = badge.file_field :image
        hr
      p
        = link_to 'Back', questions_path, class: 'btn btn-light'
        '
        = f.submit 'Create', class: 'btn btn-success'

app/views/questions/show.html.slim
.container.col-md-12
  .question.resource data-question-id=@question.id data-resource_type="question"
    = render 'section_question'

  .answers
    span.border.border-light.card     
      .card-header
        h3 Answers
      .card-body
        - if @question.answers.present?
          = render @question.answers
        - else
          p No answers yet

    - if user_signed_in? && can?(:create, Answer)
      span.border.border-light.card.mb-2
        .card-header
          h3 Add Answer

        .card-body
          .answer-errors
            = render 'shared/errors', resource: @answer

          = form_with model: [@question, @answer], class: 'new-answer' do |f|
            .form-group
              p
                = f.label :body
              p
                = f.text_area :body, rows: 3, cols: 30

              p
                = f.label :files
                ':
                = f.file_field :files, multiple: true

              = render partial: 'links/add', locals: { f: f }
              hr

              p
                = link_to 'Back', questions_path, class: 'btn btn-light'
                '
                = f.submit 'Add answer', class: 'btn btn-success'

app/views/questions/update.js.erb
$('.flash').html('<%= j render 'shared/flash' %>');
$('.edit-question').html('<%= j render 'shared/errors', resource: @question %>');

<% if @question.errors.blank? %>
  $('.question').html('<%= j render 'section_question' %>');
<% end %>