config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'oauth_callbacks',
    confirmations: 'email_confirmations'
  }

  root to: "questions#index"

  get :search, to: "search#index"

  resource :user do
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]

  concern :votable do
    member do
      post :positive, :negative
      delete :revote
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
  
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b = "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li = message  

app/views/shared/_flash.html.slim
.container  
  - flash.each do |key, message|
    = content_tag :div, message

app/views/shared/_navigation.html.slim
.container.col-xl-10
  .row-fluid
    .navbar.navbar-light.bg-light
      .navbar-brand
        = link_to 'Q&A App', root_path

        - unless user_signed_in?
          '  ->
          = link_to 'About', page_path('about')

        - if current_user&.admin?
          '  |
          = link_to 'Doorkeeper', oauth_applications_path
          '  |
          = link_to 'Sidekiq', sidekiq_web_path

      .search
        = render 'shared/search'
        
      .navbar-text
        - if user_signed_in?
          = current_user.email
          '  |
          = link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          = link_to 'Login', new_user_session_path

app/views/shared/_search.html.slim
.search-form  
  = form_tag search_path, method: :get, class: 'form-inline' do
    
    = text_field_tag :query, params[:query], class: "form-control", placeholder: 'Search'
    
    = select_tag :resource, options_for_select(SearchService::RESOURCES, params[:resource]), class: "custom-select mr-sm-6"

    = submit_tag 'Find', class: "btn btn-light"