config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'oauth_callbacks',
    confirmations: 'email_confirmations'
  }

  root to: "questions#index"

  get :search, to: "search#index"

  resource :user do
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]

  concern :votable do
    member do
      post :positive, :negative
      delete :revote
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
  
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!, only: %i[destroy]
  before_action :find_attachment, only: %i[destroy]

  authorize_resource

  def destroy
    if current_user.author?(@attachment.record)
      @attachment.purge
      flash.now[:notice] = 'File successfully deleted'
    end
  end

  private

  def find_attachment
    @attachment = ActiveStorage::Attachment.find(params[:id])
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
  TYPES = ['image/png', 'image/jpg', 'image/gif'].freeze
end

app/views/attachments/_attachment.html.slim
.attached-files
  - if resource.files.attached?
    ' Files:
    - resource.files.each do |file|
      p class="attachment-#{file.id}"
        - if AttachmentsHelper::TYPES.include?(file.content_type)
          = link_to (image_tag file, size: '200x150'), url_for(file), target: :blank
        - else
          = link_to file.filename.to_s, url_for(file), target: :blank
        '
        - if can?(:manage, file)
          = link_to 'x', attachment_path(file),
                         method: :delete,
                         remote: true

app/views/attachments/destroy.js.erb
$('.flash').html('<%= j render 'shared/flash' %>');

$('.attachment-<%= @attachment.id %>').remove();