config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'oauth_callbacks',
    confirmations: 'email_confirmations'
  }

  root to: "questions#index"

  get :search, to: "search#index"

  resource :user do
    resources :subscriptions, only: %i[create destroy]
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]

  concern :votable do
    member do
      post :positive, :negative
      delete :revote
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
  
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Voteable
  include Commentable

  belongs_to :user
  belongs_to :question, touch: true

  has_many_attached :files

  validates :body, presence: true
  validates :best, inclusion: [true, false]

  after_create_commit :notify_subscribers

  def set_best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)

      question.badge&.update!(user: user)
    end
  end

  private

  def notify_subscribers
    NewAnswerDigestJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[update destroy best]

  after_action :publish_answer, only: %i[create]

  authorize_resource
  
  def create
    @answer = @question.answers.build(answer_params.merge(question: @question))
    @answer.user = current_user
    @comment = Comment.new

    if @answer.save
      flash.now[:notice] = 'Answer successfully added'
    end
  end

  def update
    @question = @answer.question
    @comment = Comment.new

    if current_user.author?(@answer)
      @answer.update(answer_params)
      flash.now[:notice] = 'Answer successfully edited'
    end
  end

  def destroy
    if current_user.author?(@answer)
      @answer.destroy
      
      flash.now[:notice] = 'Answer successfully deleted'
    else
      render 'questions/show'
    end
  end

  def best
    @comment = Comment.new

    if current_user.author?(@answer.question)
      @answer.set_best!

      flash.now[:notice] = 'Answer set as best'
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                   links_attributes: [:id, :name, :url, :_destroy])
  end

  def answer_files
    @answer.files.map do |file|
          {
            id: file,
            name: file.filename.to_s,
            url: url_for(file) 
          }
    end
  end

  def publish_answer
    return if @answer.errors.present?

    ActionCable.server.broadcast(
      "question-#{@question.id}-answers",
        answer: @answer,
        question_author: @answer.question.user,
        files: answer_files,
        links: @answer.links
        )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: %i[index show create]
  before_action :find_answer, only: %i[show update destroy]

  authorize_resource

  def index
    @answers = @question.answers.with_attached_files
    render json: @answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.destroy
      render json: @answer, status: :ok
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  private

  def find_question
    @question ||= Question.with_attached_files.find(params[:question_id])
  end

  def find_answer
    @answer ||= Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer class="answer-#{answer.id}" data-answer-id="#{answer.id}"
  .resource data-resource_type="answer" data-resource_id="#{answer.id}"
    - cache [answer, current_user]
      p
        = answer.body
      p Author: #{answer.user.email}

      .vote
        = render partial: 'votes/vote', locals: { resource: answer }

      .links
        = render partial: 'links/list', locals: { resource: answer }

      .files
        = render partial: 'attachments/attachment', locals: { resource: answer }

      .answer-comments
        = render partial: 'comments/list', locals: { resource: answer }

      p
        - if can?(:best, answer) && !answer.best?
          = link_to 'Best answer', best_answer_path(answer),
                                   method: :patch, remote: true,
                                   class: 'btn btn-success btn-sm'

      - if can?(:update, answer)
        '
        = link_to 'Edit', '#', data: { answer_id: answer.id },
                               class: 'edit-answer-link btn btn-primary btn-sm'
        '
        = link_to 'Delete', answer_path(answer),
                            method: :delete,
                            remote: true,
                            class: 'btn btn-danger btn-sm',
                            data: { confirm: 'Are you sure?', answer_id: answer.id }

        = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
          p= f.label :body, 'Your Answer:'
          p= f.text_area :body, id: :answer_body, rows: 3, cols: 31

          p= f.label :files
          p= f.file_field :files, multiple: true, direct_upload: true
          - cache answer
            = render partial: 'links/add', locals: { f: f }

          br
          = f.submit 'Save', class: 'btn btn-success'
hr

app/views/answers/_list.html.slim
- @question.answers.each do |answer|
  p = answer.body
  - if current_user&.author?(answer)
    = link_to 'Delete answer', answer,
      method: :delete, data: { confirm: 'Are you sure?' }

- if user_signed_in?
  b = 'Add Answer'
  = form_with model: [@question, @answer], local: true do |f|
    = render 'shared/errors', resource: @answer

    = f.label :body
    = f.text_area :body

    br
    = f.submit 'Add answer'

app/views/answers/best.js.erb
$('.answer-errors').html('');
$('.flash').html('');

$('.answers .card-body').html("<%= j render @answer.question.answers %>");
$('.flash').html("<%= j render 'shared/flash' %>");

app/views/answers/create.js.erb
$('.flash').html('<%= j render 'shared/flash' %>');
$('.answer-errors').html('<%= j render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers .card-body').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.flash').html('<%= j render 'shared/flash' %>');

$('.answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
$('.flash').html('<%= j render 'shared/flash' %>');
$('.answer-errors').html('<%= j render 'shared/errors', resource: @answer %>');

<% if @answer.errors.blank? %>
  $('.answers .card-body').html('<%= j render @question.answers %>');
<% end %>